set_property SRC_FILE_INFO {cfile:D:/2MASTER/Vivado_Project/Axi_can_lite_fullnote/GUUUUUU/Axi_Can_Lite.srcs/constrs_1/new/can_lite.xdc rfile:../../../Axi_Can_Lite.srcs/constrs_1/new/can_lite.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports can_rx]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A11 [get_ports can_tx]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF12 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE5 [get_ports sys_clk_p]
